---
- name: Testing sysctl configuration
  hosts: 127.0.0.1
  connection: local
  become: true
  become_method: sudo
  tasks:
    - name: Install gdb packages
      apt: name={{ item }} install_recommends=no update_cache=true force_apt_get=true
      with_items:
        - gdbserver
        - gdb

    - name: Enabling ptrace
      sysctl:
        name: kernel.yama.ptrace_scope
        value: '0'
        sysctl_file: /etc/sysctl.d/10-ptrace.conf
        reload: yes

