---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  #hosts: instance
  gather_facts: false
  tasks:
  #- name: Example assertion
  #  ansible.builtin.assert:
  #    that: true
  - name: Verify nginx is serving web requests
    ansible.builtin.uri:
      url: http://localhost/
      status_code: 200
