---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
  - name: Verify nginx is serving web requests
    ansible.builtin.uri:
      url: http://localhost/
      status_code: 200
